apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  ports:
    - port: 3232
  selector:
    app: api
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: api
        tier: frontend
    spec:
      containers:
        - name: master
          image: local/app
          imagePullPolicy: Never
          args:
            - api
          ports:
            - containerPort: 3232
              name: api
          env:
            - name: REDIS_ADDRESS
              value: "redis:6379"
            - name: MYSQL_PASSWORD
              value: "keda-talk"
          resources:
            limits:
              cpu: "0.1"